apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: gkonradt@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    # this solver handles example.org challenges
    # and uses explicit credentials
    - selector:
        dnsZones:
          - "gkon.link"
      dns01:
        route53:
          region: eu-central-1
          accessKeyID: AKIA45ZRWTR3EKDIJSU5
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
