{
 "title": "Node Temperatures",
 "description": "Thermal sensor data from a node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_hwmon_temp_celsius{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pi4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature Pi4",
   "type": "timeseries",
   "description": "Pi4: 192.168.1.161",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.161:9100\"}",
     "legendFormat": "{{chip}}-{{sensor}}"
    },
    {
     "expr": "node_thermal_zone_temp{instance=\"192.168.1.161:9100\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Curr. Temperature Pi4",
   "type": "gauge",
   "description": "Pi4: 192.168.1.161",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{instance=\"192.168.1.161:9100\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Pi3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature Pi3",
   "type": "timeseries",
   "description": "Pi3: 192.168.1.4",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.4:9100\"}",
     "legendFormat": "{{chip}}-{{sensor}}"
    },
    {
     "expr": "node_thermal_zone_temp{instance=\"192.168.1.4:9100\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Curr. Temperature Pi3",
   "type": "gauge",
   "description": "Pi3: 192.168.1.4",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{instance=\"192.168.1.4:9100\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}